# Site settings
title: stevehocking.co.uk
email: steve@stevehocking.co.uk
description: ""
baseurl: ""
url: "https://www.stevehocking.co.uk"
github-username: steve-codemunkies
twitter-username: codemunkies
twitter-personal-username: SteveHocking
stackoverflow-username: steve
stackoverflow-userid: 747649

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

include:
  - keybase.txt
  - public.key
exclude:
  - .devcontainer
  - .github
  - .vscode
  - cdk
  - js-function
