# Site settings
title: codemunkies
email: steve@codemunki.es
description: ""
baseurl: ""
url: "http://yourdomain.com"
github-username: steve-codemunkies
twitter-username: codemunkies

# Build settings
markdown: kramdown
permalink: pretty
