version: '3.0'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.4-bullseye"
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    container_name: codemunkies-github
    network_mode: service:plantuml

  plantuml:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    ports:
      - 8080:8080
    environment:
      - BASE_URL=plantuml